=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Libraries/bulletml.dtd
<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>
<!ELEMENT changeSpeed (speed, term)>
<!ELEMENT changeColor (color, term)>
<!ELEMENT changeScale (scale, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none | vertical | horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef)+)>

<!ELEMENT accel
  (
    (((horizontal, vertical?) | (horizontal?, vertical)), term) |
    (((vertical, horizontal?) | (vertical?, horizontal)), term) |
    ((horizontal, term, vertical?) | (horizontal?, term, vertical)) |
    ((vertical, term, horizontal?) | (vertical?, term, horizontal)) |
    (term, ((horizontal, vertical?) | (horizontal?, vertical))) |
    (term, ((vertical, horizontal?) | (vertical?, horizontal)))
  )
>
<!ATTLIST accel label CDATA #IMPLIED>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (accel | changeDirection | changeSpeed | changeColor | changeScale | repeat | wait | (fire | fireRef) | (action | actionRef) | vanish)*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT scale (#PCDATA)>
<!ATTLIST scale type (absolute|relative|sequence) "absolute">

<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT opacity (#PCDATA)>
<!ELEMENT color (red?, green?, blue?, alpha?, opacity?)>

<!ELEMENT sprite (#PCDATA)>

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, sprite?, color?, scale?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT fire
  (
    (direction?, speed?, (bullet | bulletRef)) |
    (speed?, direction?, (bullet | bulletRef)) |
    (direction?, (bullet | bulletRef), speed?) |
    (speed?, (bullet | bulletRef), direction?) |
    ((bullet | bulletRef), direction?, speed?) |
    ((bullet | bulletRef), speed?, direction?) |
    (direction?, speed?, scale?, sprite?, (bullet | bulletRef))
  )
>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/45°.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <action>
      <fire>
        <bullet>
          <direction type="absolute">0</direction>
          <speed>1</speed>
          <sprite>1</sprite>
        </bullet>
      </fire>
      <wait>30</wait>
      <repeat>
        <times>0</times>
        <action>
          <fire>
            <bullet>
              <direction type="sequence">45</direction>
              <speed>1</speed>
              <sprite>1</sprite>
            </bullet>
          </fire>
          <wait>30</wait>
        </action>
      </repeat>
    </action>

  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Patterns/sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>60</times>
      <action>
        <repeat>
          <times>8</times>
          <action>
            <fire>
              <bullet>
                <direction type="sequence">46</direction>
                <speed>2</speed>
                <action>
                  <changeDirection>
                    <direction type="relative">360</direction>
                    <term>250</term>
                  </changeDirection>
                  <wait>250</wait>
                  <changeSpeed>
                    <speed>0</speed>
                    <term>250</term>
                  </changeSpeed>
                  <changeDirection>
                    <direction type="relative">-180</direction>
                    <term>250</term>
                  </changeDirection>
                  <wait>250</wait>
                  <changeSpeed>
                    <speed>3</speed>
                    <term>100</term>
                  </changeSpeed>
                </action>
              </bullet>
            </fire>
          </action>
        </repeat>
        <wait>5</wait>
      </action>
    </repeat>
  </action>
</bulletml>
