=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Libraries/bulletml.dtd
<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>
<!ELEMENT changeSpeed (speed, term)>
<!ELEMENT changeColor (color, term)>
<!ELEMENT changeScale (scale, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none | vertical | horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef)+)>

<!ELEMENT accel
  (
    (((horizontal, vertical?) | (horizontal?, vertical)), term) |
    (((vertical, horizontal?) | (vertical?, horizontal)), term) |
    ((horizontal, term, vertical?) | (horizontal?, term, vertical)) |
    ((vertical, term, horizontal?) | (vertical?, term, horizontal)) |
    (term, ((horizontal, vertical?) | (horizontal?, vertical))) |
    (term, ((vertical, horizontal?) | (vertical?, horizontal)))
  )
>
<!ATTLIST accel label CDATA #IMPLIED>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (accel | changeDirection | changeSpeed | changeColor | changeScale | repeat | wait | (fire | fireRef) | (action | actionRef) | vanish)*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT scale (#PCDATA)>
<!ATTLIST scale type (absolute|relative|sequence) "absolute">

<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT opacity (#PCDATA)>
<!ELEMENT color (red?, green?, blue?, alpha?, opacity?)>

<!ELEMENT sprite (#PCDATA)>

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, sprite?, color?, scale?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT fire
  (
    (direction?, speed?, (bullet | bulletRef)) |
    (speed?, direction?, (bullet | bulletRef)) |
    (direction?, (bullet | bulletRef), speed?) |
    (speed?, (bullet | bulletRef), direction?) |
    ((bullet | bulletRef), direction?, speed?) |
    ((bullet | bulletRef), speed?, direction?) |
    (direction?, speed?, scale?, sprite?, (bullet | bulletRef))
  )
>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/Benchmark.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>10000</times>
      <action>
        <repeat>
          <times>10</times>
          <action>
            <fire>
              <bullet>
                <direction type="absolute">$rand * 360</direction>
                <speed type="absolute">0.5</speed>
                <action>
                  <changeSpeed>
                    <speed>0</speed>
                    <term>10000</term>
                  </changeSpeed>
                </action>
              </bullet>
            </fire>
          </action>
        </repeat>
        <wait>1</wait>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Resources/Patterns/Benchmark.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>10000</times>
      <action>
        <fire>
          <bullet>
            <direction type="absolute">$rand * 360</direction>
            <speed type="absolute">0.001 + $rand * 0.1</speed>
            <action>
              <changeSpeed>
                <speed>0</speed>
                <term>10000</term>
              </changeSpeed>
            </action>
          </bullet>
        </fire>
        <wait>1</wait>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/Circle.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>0</times>
      <action>
        <repeat>
          <times>10</times>
          <action>
            <fire>
            <bullet>
              <direction type="sequence">82</direction>
              <speed type="absolute">15</speed>
              <sprite>2</sprite>
              <color>
                <red>0.78</red>
                <green>0</green>
                <blue>0</blue>
              </color>
              <action>
                <changeSpeed>
                  <speed>0</speed>
                  <term>50</term>
                </changeSpeed>
                <wait>500</wait>
                <changeSpeed>
                  <speed>1</speed>
                  <term>0</term>
                </changeSpeed>
                <changeDirection>
                  <direction type="relative">-30 + $rand * 60</direction>
                  <term>0</term>
                </changeDirection>
              </action>
            </bullet>
            </fire>
            <wait>0</wait>
          </action>
        </repeat>
        <wait>2</wait>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Resources/Patterns/45°.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <action>
      <repeat>
        <times>0</times>
        <action>
          <fire>
            <bullet>
              <direction type="sequence">45</direction>
              <speed>1</speed>
              <sprite>1</sprite>
            </bullet>
          </fire>
          <wait>60</wait>
        </action>
      </repeat>
    </action>

  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/Aim.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>0</times>
      <action>
        <fire>
          <bullet>
            <direction type="aim">0</direction>
            <speed>1</speed>
            <action>
              <changeSpeed>
                <speed>20</speed>
                <term>60</term>
              </changeSpeed>
            </action>
          </bullet>
        </fire>
        <wait>5</wait>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/Color.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>0</times>
      <action>
        <repeat>
          <times>8</times>
          <action>
            <fire>
              <direction type="sequence">46</direction>
              <bulletRef label="color" />
            </fire>
          </action>
        </repeat>
        <wait>10</wait>
      </action>
    </repeat>
  </action>

  <bullet label="color">
      <speed>1</speed>
      <color>
        <red>1.0</red>
        <green>0.0</green>
        <blue>0.0</blue>
        <alpha>1.0</alpha>
        <opacity>1.0</opacity>
      </color>
      <action>
        <changeColor>
          <color>
            <opacity>0.0</opacity>
          </color>
          <term>20</term>
        </changeColor>
        <wait>50</wait>
        <changeColor>
          <color>
            <red>0.0</red>
            <green>1.0</green>
            <blue>0.0</blue>
            <alpha>1.0</alpha>
            <opacity>1.0</opacity>
          </color>
          <term>20</term>
        </changeColor>
        <wait>50</wait>
        <changeColor>
          <color>
            <opacity>0.0</opacity>
          </color>
          <term>20</term>
        </changeColor>
        <wait>50</wait>
        <changeColor>
          <color>
            <red>0.0</red>
            <green>0.0</green>
            <blue>1.0</blue>
            <alpha>1.0</alpha>
            <opacity>1.0</opacity>
          </color>
          <term>20</term>
        </changeColor>
        <wait>50</wait>
        <changeColor>
          <color>
            <red>$rand</red>
            <green>$rand</green>
            <blue>$rand</blue>
            <alpha>1.0</alpha>
            <opacity>1.0</opacity>
          </color>
          <term>100</term>
        </changeColor>
      </action>
  </bullet>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Demo/Resources/Patterns/Sprite.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <fire>
      <bullet>
        <speed>5</speed>
        <action>
          <repeat>
            <times>0</times>
            <action>
              <fire>
                <bullet>
                  <direction type="absolute">$rand * 360</direction>
                  <speed>0</speed>
                  <sprite>1</sprite>
                  <actionRef label="explosion">
                    <param>$rand * 7</param>
                  </actionRef>
                </bullet>
              </fire>
              <wait>1</wait>
              <changeDirection>
                <direction type="aim">0</direction>
                <term>1</term>
              </changeDirection>
            </action>
          </repeat>
        </action>
      </bullet>
    </fire>
  </action>

  <action label="explosion">
    <wait>100</wait>
    <changeSpeed>
      <speed>5</speed>
      <term>100</term>
    </changeSpeed>
    <changeColor>
      <color>
        <red>$rand</red>
        <green>$rand</green>
        <blue>$rand</blue>
      </color>
      <term>100</term>
    </changeColor>
    <wait>100</wait>
    <repeat>
      <times>10</times>
      <action>
        <fire>
          <bullet>
            <direction type="sequence">36</direction>
            <speed>5</speed>
            <sprite>$1</sprite>
            <color>
              <red>$rand</red>
              <green>$rand</green>
              <blue>$rand</blue>
            </color>
          </bullet>
        </fire>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML-Unity/BulletML-Unity/Assets/Sample/Resources/Patterns/ChangeScale.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>0</times>
      <action>
        <fire>
          <bulletRef label="pulse">
          </bulletRef>
        </fire>
        <wait>1</wait>
      </action>
    </repeat>
  </action>

  <bullet label="pulse">
    <direction type="sequence">5</direction>
    <speed>1</speed>
    <scale>0.5</scale>
    <action>
      <repeat>
        <times>0</times>
        <action>
          <changeScale>
            <scale>5</scale>
            <term>50</term>
          </changeScale>
          <wait>50</wait>
          <changeScale>
            <scale>0.5</scale>
            <term>50</term>
          </changeScale>
          <wait>50</wait>
        </action>
      </repeat>
    </action>
  </bullet>
</bulletml>
